# Change these first
owner: transverse-dev # Your GitHub username
repo: evoclass-status # Your GitHub repository name


sites:
  - name: 에보클래스 수업관리
    url: https://evoclass.ai
  - name: 에보클래스 화상회의
    url: https://room.evoclass.io
  - name: 에보클래스 서버
    url: https://api.evoclass.ai/swagger

status-website:
  cname: status.evoclass.ai
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: evoclass 서비스 상태
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: 사이트 바로가기
      href: https://evoclass.ai

robotsText: "User-agent: * \n Disallow: /"
